spring:
  datasource:
    url: jdbc:h2:file:C:/Users/leona/test
    driverClassName: org.h2.Driver
    username: leonardo
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update